sudo: false

language: php

php:
- '7.1'

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install --no-suggest
  - ./vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  - ./vendor/drush/drush/unish.sut.php
  - ./tests/sut.cp.php

script:
  - ./vendor/bin/phpcs --standard=PSR2 . --ignore='vendor,tests/coverage'
  - ./vendor/bin/phpunit
